export const schemaErrors = {
   NOT_AN_ARRAY: 'NOT_AN_ARRAY',
   NOT_AN_OBJECT: 'NOT_AN_OBJECT',
   NOT_A_STRING: 'NOT_A_STRING',
   INVALID_STRING_FORMAT: 'INVALID_STRING_FORMAT',
   STRING_MIN_LENGTH: 'STRING_MIN_LENGTH',
   STRING_MAX_LENGTH: 'STRING_MAX_LENGTH',
   ARRAY_MIN_LENGTH: 'ARRAY_MIN_LENGTH',
   ARRAY_MAX_LENGTH: 'ARRAY_MAX_LENGTH',
   NOT_A_NUMBER: 'NOT_A_NUMBER',
   NOT_AN_INTEGER: 'NOT_AN_INTEGER',
   NUMBER_MINIMUM: 'NUMBER_MINIMUM',
   NUMBER_MAXIMUM: 'NUMBER_MAXIMUM',
   NOT_A_BOOLEAN: 'NOT_A_BOOLEAN',
   NOT_AN_ENUM: 'NOT_AN_ENUM',
   REQUIRED: 'REQUIRED',
   NOT_ALLOW_NULL: 'NOT_ALLOW_NULL',
   NOT_ALLOW_PROPERTY: 'NOT_ALLOW_PROPERTY',
   NOT_SUITABLE_ARRAY: 'NOT_SUITABLE_ARRAY',
   NOT_AN_UNIQUE_ARRAY: 'NOT_AN_UNIQUE_ARRAY',
   NOT_STRONG_PASSWORD: 'NOT_STRONG_PASSWORD',
};

export const UJS_CLASS_PROPERTIES = '__UJS_CLASS_PROPERTIES__';
export const UJS_SWAGGER_PROPERTIES_ARRAY = 'swagger/apiModelPropertiesArray';
export const UJS_SWAGGER_PROPERTIES_MODEL = 'swagger/apiModelProperties';
